### ISSUE TITLE
项目启动点击登陆报500错误

### ISSUE THREAD

**Issue by RafaelGuo** [slimkit/plus#742]
在windows下部署项目后，访问http://localhost:8000，点击登陆后报500错误，看了下日志:local.ERROR: cURL error 7: Failed to connect to localhost port 80: Connection refused,想问下这个如何解决？

**Comment by boxshadow** [comment]
@RafaelGuo 抱歉, 需要贴一下具体的日志, 如果是 ngxin/apache设置了监听端口是8000,需要设置 storage/configure/plus.yml 里的url为你本地访问的项目地址,
因为不清楚具体的环境配置, 最好是贴上你的错误日志

thx

**Comment by WaJueJiPrince** [comment]
![Snipaste_2019-07-08_17-34-54.png](https://i.loli.net/2019/07/08/5d230e4e0785194478.png)

**Comment by boxshadow** [comment]
@WaJueJiPrince 这个截图把所有的错误细节都隐藏了, 请帖一下源码根目录下 storage/logs/当天的日志文件

**Comment by DaNiu-Luck** [comment]
[2019-07-29 04:47:55] local.ERROR: SQLSTATE[HY000] [1045] Access denied for user 'plus'@'localhost' (using password: NO) (SQL: insert into `telescope_entries` (`batch_id`, `content`, `created_at`, `type`, `uuid`) values (8e4775a4-7a37-4875-9218-6bc88a3d35d2, {"command":"key:generate","exit_code":0,"arguments":{"command":"key:generate"},"options":{"show":false,"force":false,"help":false,"quiet":false,"verbose":false,"version":false,"ansi":false,"no-ansi":false,"no-interaction":false,"env":null},"hostname":"VM-0-12-debian"}, 2019-07-29 04:47:55, command, 8e4775a4-791b-4670-9bea-52ec94533668)) {"exception":"[object] (Illuminate\\Database\\QueryException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'plus'@'localhost' (using password: NO) (SQL: insert into `telescope_entries` (`batch_id`, `content`, `created_at`, `type`, `uuid`) values (8e4775a4-7a37-4875-9218-6bc88a3d35d2, {\"command\":\"key:generate\",\"exit_code\":0,\"arguments\":{\"command\":\"key:generate\"},\"options\":{\"show\":false,\"force\":false,\"help\":false,\"quiet\":false,\"verbose\":false,\"version\":false,\"ansi\":false,\"no-ansi\":false,\"no-interaction\":false,\"env\":null},\"hostname\":\"VM-0-12-debian\"}, 2019-07-29 04:47:55, command, 8e4775a4-791b-4670-9bea-52ec94533668)) at /var/www/plus-2.3.0/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664, Doctrine\\DBAL\\Driver\\PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'plus'@'localhost' (using password: NO) at /var/www/plus-2.3.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31, PDOException(code: 1045): SQLSTATE[HY000] [1045] Access denied for user 'plus'@'localhost' (using password: NO) at /var/www/plus-2.3.0/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27)
[stacktrace]
#0 /var/www/plus-2.3.0/vendor/laravel/framework/src/Illuminate/Database/Connection.php(624): Illuminate\\Database\\Connection->runQueryCallback('insert into `te...', Array, Object(Closure))
#1 /var/www/plus-2.3.0/vendor/laravel/framework/src/Illuminate/Database/Connection.php(459): Illuminate\\Database\\Connection->run('insert into `te...', Array, Object(Closure))
#2 /var/www/plus-2.3.0/vendor/laravel/framework/src/Illuminate/Database/Connection.php(411): Illuminate\\Database\\Connection->statement('insert into `te...', Array)
#3 /var/www/plus-2.3.0/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2611): Illuminate\\Database\\Connection->insert('insert into `te...', Array)
#4 /var/www/plus-2.3.0/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(121): Illuminate\\Database\\Query\\Builder->insert(Array)
#5 /var/www/plus-2.3.0/vendor/laravel/framework/src/Illuminate/Support/Collection.php(419): Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->Laravel\\Telescope\\Storage\\{closure}(Object(Illuminate\\Support\\Collection), 0)
#6 /var/www/plus-2.3.0/vendor/laravel/telescope/src/Storage/DatabaseEntriesRepository.php(122): Illuminate\\Support\\Collection->each(Object(Closure))
#7 /var/www/plus-2.3.0/vendor/laravel/telescope/src/Telescope.php(553): Laravel\\Telescope\\Storage\\DatabaseEntriesRepository->store(Object(Illuminate\\Support\\Collection))
#8 /var/www/plus-2.3.0/vendor/laravel/telescope/src/ListensForStorageOpportunities.php(44): Laravel\\Telescope\\Telescope::store(Object(Laravel\\Telescope\\Storage\\DatabaseEntriesRepository))
#9 [internal function]: Laravel\\Telescope\\Telescope::Laravel\\Telescope\\{closure}()
#10 /var/www/plus-2.3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(29): call_user_func_array(Object(Closure), Array)
#11 /var/www/plus-2.3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(75): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#12 /var/www/plus-2.3.0/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(31): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Zhiyi\\Plus\\Application), Object(Closure), Object(Closure))
#13 /var/www/plus-2.3.0/vendor/laravel/framework/src/Illuminate/Container/Container.php(572): Illuminate\\Container\\BoundMethod::call(Object(Zhiyi\\Plus\\Application), Object(Closure), Array, NULL)
#14 /var/www/plus-2.3.0/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(991): Illuminate\\Container\\Container->call(Object(Closure))
#15 /var/www/plus-2.3.0/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(149): Illuminate\\Foundation\\Application->terminate()
#16 /var/www/plus-2.3.0/artisan(51): Illuminate\\Foundation\\Console\\Kernel->terminate(Object(Symfony\\Component\\Console\\Input\\ArgvInput), 0)
#17 {main}
"}

**Comment by DaNiu-Luck** [comment]
@boxshadow 你好，我部署好了之后，访问首页正常，访问/auth/login 或者 /installer 都报错。上面是错误信息

**Comment by boxshadow** [comment]
@DaNiu-Luck

>  [2019-07-29 04:47:55] local.ERROR: SQLSTATE[HY000] [1045] Access denied for user 'plus'@'localhost' (using password: NO) 

第一句就已经提示数据库连接被拒绝, 账号密码错误

**Comment by yingliangzhang** [comment]
@RafaelGuo 你好我遇到了和你一样的问题，windows 500， cURL error 7: Failed to connect to localhost port 80: Connection refused 请问之后你是如何解决的？
