### ISSUE TITLE
http://127.0.0.1:8000/auth/login returns 500 (Windows)

### ISSUE THREAD

**Issue by yingliangzhang** [slimkit/plus#837]
**Describe the bug**
按照Readme setup以后访问 http://127.0.0.1:8000/auth/login 返回500。首页可以显示，数据库migration和seed也没有问题

**To Reproduce**
1. `php artisan serve`
2. Go to http://127.0.0.1:8000/auth/login

**Expected behavior**
See login page

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser Chrome

**Additional context**
Logs:
```
[2020-01-03 09:32:55] local.ERROR: cURL error 7: Failed to connect to localhost port 80: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) {"exception":"[object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 7: Failed to connect to localhost port 80: Connection refused (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) at C:\\Dev\\plus\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlFactory.php:200)
[stacktrace]
#0 C:\\Dev\\plus\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlFactory.php(155): GuzzleHttp\\Handler\\CurlFactory::createRejection()
#1 C:\\Dev\\plus\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlFactory.php(105): GuzzleHttp\\Handler\\CurlFactory::finishError()
#2 C:\\Dev\\plus\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\CurlHandler.php(43): GuzzleHttp\\Handler\\CurlFactory::finish()
#3 C:\\Dev\\plus\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke()
#4 C:\\Dev\\plus\\vendor\\guzzlehttp\\guzzle\\src\\Handler\\Proxy.php(51): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#5 C:\\Dev\\plus\\vendor\\guzzlehttp\\guzzle\\src\\PrepareBodyMiddleware.php(37): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}()
#6 C:\\Dev\\plus\\vendor\\guzzlehttp\\guzzle\\src\\Middleware.php(29): GuzzleHttp\\PrepareBodyMiddleware->__invoke()
#7 C:\\Dev\\plus\\vendor\\guzzlehttp\\guzzle\\src\\RedirectMiddleware.php(70): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#8 C:\\Dev\\plus\\vendor\\guzzlehttp\\guzzle\\src\\Middleware.php(57): GuzzleHttp\\RedirectMiddleware->__invoke()
#9 C:\\Dev\\plus\\vendor\\guzzlehttp\\guzzle\\src\\HandlerStack.php(71): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}()
#10 C:\\Dev\\plus\\vendor\\guzzlehttp\\guzzle\\src\\Client.php(361): GuzzleHttp\\HandlerStack->__invoke()
#11 C:\\Dev\\plus\\vendor\\guzzlehttp\\guzzle\\src\\Client.php(163): GuzzleHttp\\Client->transfer()
#12 C:\\Dev\\plus\\vendor\\guzzlehttp\\guzzle\\src\\Client.php(183): GuzzleHttp\\Client->requestAsync()
#13 C:\\Dev\\plus\\packages\\zhiyicx-plus-pc\\src\\helpers.php(124): GuzzleHttp\\Client->request()
#14 C:\\Dev\\plus\\packages\\zhiyicx-plus-pc\\src\\Controllers\\BaseController.php(65): Zhiyi\\Component\\ZhiyiPlus\\PlusComponentPc\\api()
#15 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(145): Zhiyi\\Component\\ZhiyiPlus\\PlusComponentPc\\Controllers\\BaseController->Zhiyi\\Component\\ZhiyiPlus\\PlusComponentPc\\Controllers\\{closure}()
#16 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Middleware\\SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#18 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#19 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#21 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle()
#22 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#23 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\View\\Middleware\\ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#24 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle()
#25 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#26 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Session\\Middleware\\StartSession.php(63): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#27 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle()
#28 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#30 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle()
#31 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Cookie\\Middleware\\EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#33 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle()
#34 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#36 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(684): Illuminate\\Pipeline\\Pipeline->then()
#37 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(659): Illuminate\\Routing\\Router->runRouteWithinStack()
#38 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(625): Illuminate\\Routing\\Router->runRoute()
#39 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Router.php(614): Illuminate\\Routing\\Router->dispatchToRoute()
#40 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(176): Illuminate\\Routing\\Router->dispatch()
#41 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#42 C:\\Dev\\plus\\vendor\\fideloper\\proxy\\src\\TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#43 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle()
#44 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#45 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#46 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#47 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#48 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#49 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#50 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#51 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#52 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#53 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#54 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#55 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle()
#56 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#57 C:\\Dev\\plus\\vendor\\medz\\cors\\src\\Laravel\\Middleware\\Cors.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#58 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(163): Medz\\Cors\\Laravel\\Middleware\\Cors->handle()
#59 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Routing\\Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#60 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Pipeline\\Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}()
#61 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then()
#62 C:\\Dev\\plus\\vendor\\laravel\\framework\\src\\Illuminate\\Foundation\\Http\\Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#63 C:\\Dev\\plus\\public\\index.php(64): Illuminate\\Foundation\\Http\\Kernel->handle()
#64 C:\\Dev\\plus\\server.php(30): require_once('C:\\\\Dev\\\\plus\\\\pub...')
#65 {main}
"} 
```

**Comment by yingliangzhang** [comment]
换用Laravel Homestead后没有这个问题了
